# Generated by Django 3.2.16 on 2024-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programer',
            name='image',
            field=models.ImageField(upload_to='media/programers'),
        ),
    ]
